/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

/**
 *
 * @author Sebastian
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campo = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        invertir = new javax.swing.JButton();
        potencia = new javax.swing.JButton();
        division = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        multiplicacion = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        resto = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        decimal = new javax.swing.JButton();
        igualdad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setText("C");
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });

        invertir.setBackground(new java.awt.Color(255, 255, 255));
        invertir.setText("+/-");
        invertir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invertirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                invertirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                invertirMouseExited(evt);
            }
        });

        potencia.setBackground(new java.awt.Color(255, 255, 255));
        potencia.setText("^");
        potencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                potenciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                potenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                potenciaMouseExited(evt);
            }
        });

        division.setBackground(new java.awt.Color(255, 255, 255));
        division.setText("/");
        division.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divisionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                divisionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                divisionMouseExited(evt);
            }
        });

        num1.setBackground(new java.awt.Color(255, 255, 255));
        num1.setText("1");
        num1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                num1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                num1MouseExited(evt);
            }
        });

        num2.setBackground(new java.awt.Color(255, 255, 255));
        num2.setText("2");
        num2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                num2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                num2MouseExited(evt);
            }
        });

        num3.setBackground(new java.awt.Color(255, 255, 255));
        num3.setText("3");
        num3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                num3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                num3MouseExited(evt);
            }
        });

        multiplicacion.setBackground(new java.awt.Color(255, 255, 255));
        multiplicacion.setText("x");
        multiplicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplicacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                multiplicacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                multiplicacionMouseExited(evt);
            }
        });

        num4.setBackground(new java.awt.Color(255, 255, 255));
        num4.setText("4");
        num4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                num4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                num4MouseExited(evt);
            }
        });

        num5.setBackground(new java.awt.Color(255, 255, 255));
        num5.setText("5");
        num5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                num5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                num5MouseExited(evt);
            }
        });

        num6.setBackground(new java.awt.Color(255, 255, 255));
        num6.setText("6");
        num6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                num6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                num6MouseExited(evt);
            }
        });

        resta.setBackground(new java.awt.Color(255, 255, 255));
        resta.setText("-");
        resta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                restaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restaMouseExited(evt);
            }
        });

        num7.setBackground(new java.awt.Color(255, 255, 255));
        num7.setText("7");
        num7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                num7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                num7MouseExited(evt);
            }
        });

        num8.setBackground(new java.awt.Color(255, 255, 255));
        num8.setText("8");
        num8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                num8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                num8MouseExited(evt);
            }
        });

        num9.setBackground(new java.awt.Color(255, 255, 255));
        num9.setText("9");
        num9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                num9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                num9MouseExited(evt);
            }
        });

        suma.setBackground(new java.awt.Color(255, 255, 255));
        suma.setText("+");
        suma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sumaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sumaMouseExited(evt);
            }
        });

        resto.setBackground(new java.awt.Color(255, 255, 255));
        resto.setText("%");
        resto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                restoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restoMouseExited(evt);
            }
        });

        num0.setBackground(new java.awt.Color(255, 255, 255));
        num0.setText("0");
        num0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num0MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                num0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                num0MouseExited(evt);
            }
        });

        decimal.setBackground(new java.awt.Color(255, 255, 255));
        decimal.setText(".");
        decimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decimalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                decimalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                decimalMouseExited(evt);
            }
        });

        igualdad.setBackground(new java.awt.Color(255, 255, 255));
        igualdad.setText("=");
        igualdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                igualdadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                igualdadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                igualdadMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(campo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(resto, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(num1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(num4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(num7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(num0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(invertir, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(num2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(num5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(num8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(decimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(num6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(num3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(potencia, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(num9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(division, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(multiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(suma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(igualdad, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(invertir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(potencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(division, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(num1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(num2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(multiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(num4, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(num5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(num7, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(num8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resto, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(num0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(decimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(igualdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        campo.setText("");
    }//GEN-LAST:event_clearMouseClicked

    private void num1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num1MouseClicked
        campo.setText(campo.getText()+"1");
    }//GEN-LAST:event_num1MouseClicked

    private void num2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num2MouseClicked
        campo.setText(campo.getText()+"2");
    }//GEN-LAST:event_num2MouseClicked

    private void num3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num3MouseClicked
        campo.setText(campo.getText()+"3");
    }//GEN-LAST:event_num3MouseClicked

    private void num4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num4MouseClicked
        campo.setText(campo.getText()+"4");
    }//GEN-LAST:event_num4MouseClicked

    private void num5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num5MouseClicked
        campo.setText(campo.getText()+"5");
    }//GEN-LAST:event_num5MouseClicked

    private void num6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num6MouseClicked
        campo.setText(campo.getText()+"6");
    }//GEN-LAST:event_num6MouseClicked

    private void num7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num7MouseClicked
        campo.setText(campo.getText()+"7");
    }//GEN-LAST:event_num7MouseClicked

    private void num8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num8MouseClicked
        campo.setText(campo.getText()+"8");
    }//GEN-LAST:event_num8MouseClicked

    private void num9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num9MouseClicked
        campo.setText(campo.getText()+"9");
    }//GEN-LAST:event_num9MouseClicked

    private void num0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num0MouseClicked
        campo.setText(campo.getText()+"0");
    }//GEN-LAST:event_num0MouseClicked

    private void invertirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invertirMouseClicked
        double n = Double.parseDouble(campo.getText());
        campo.setText(Double.toString(n*-1));
    }//GEN-LAST:event_invertirMouseClicked

    private void potenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potenciaMouseClicked
        campo.setText(campo.getText()+"^");
    }//GEN-LAST:event_potenciaMouseClicked

    private void divisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisionMouseClicked
        campo.setText(campo.getText()+"/");
    }//GEN-LAST:event_divisionMouseClicked

    private void multiplicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicacionMouseClicked
        campo.setText(campo.getText()+"x");
    }//GEN-LAST:event_multiplicacionMouseClicked

    private void restaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaMouseClicked
        campo.setText(campo.getText()+"-");
    }//GEN-LAST:event_restaMouseClicked

    private void sumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumaMouseClicked
        campo.setText(campo.getText()+"+");
    }//GEN-LAST:event_sumaMouseClicked

    private void restoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restoMouseClicked
        campo.setText(campo.getText()+"%");
    }//GEN-LAST:event_restoMouseClicked

    private void decimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decimalMouseClicked
        campo.setText(campo.getText()+".");
    }//GEN-LAST:event_decimalMouseClicked

    private void igualdadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igualdadMouseClicked
        String s=campo.getText();
        if(s.contains("^")){
            try{
                String a = s.substring(0, s.indexOf("^"));
                String b = s.substring(s.indexOf("^")+1, s.length());
                double resultado = Math.pow(Double.parseDouble(a), Double.parseDouble(b));
                campo.setText(Double.toString(resultado));
            }catch(Exception e){
                campo.setText("Synthax error");
            }
        }
        
        if(s.contains("/")){
            try{
                String a = s.substring(0, s.indexOf("/"));
                String b = s.substring(s.indexOf("/")+1, s.length());
                double resultado = Double.parseDouble(a) / Double.parseDouble(b);
                campo.setText(Double.toString(resultado));
            }catch(Exception e){
                campo.setText("Synthax error");
            }     
        }
        
        if(s.contains("x")){
            try{
                String a = s.substring(0, s.indexOf("x"));
                String b = s.substring(s.indexOf("x")+1, s.length());
                double resultado = Double.parseDouble(a) * Double.parseDouble(b);
                campo.setText(Double.toString(resultado));
            }catch(Exception e){
                campo.setText("Synthax error");
            }
        }
        
        if(s.indexOf("-", 1)!=-1){
            try{
                String a = s.substring(0, s.indexOf("-", 1));
                String b = s.substring(s.indexOf("-", 1)+1, s.length());
                double resultado = Double.parseDouble(a) - Double.parseDouble(b);
                campo.setText(Double.toString(resultado));
            }catch(Exception e){
                campo.setText("Synthax error");
            }
        }
        
        if(s.indexOf("+", 1)!=-1){
            try{
                String a = s.substring(0, s.indexOf("+", 1));
                String b = s.substring(s.indexOf("+", 1)+1, s.length());
                double resultado = Double.parseDouble(a) + Double.parseDouble(b);
                campo.setText(Double.toString(resultado));
            }catch(Exception e){
                campo.setText("Synthax error");
            }
        }
        
        if(s.contains("%")){
            try{
               String a = s.substring(0, s.indexOf("%"));
                String b = s.substring(s.indexOf("%")+1, s.length());
                double resultado = Double.parseDouble(a) % Double.parseDouble(b);
                campo.setText(Double.toString(resultado)); 
            }catch(Exception e){
                campo.setText("Synthax error");
            }   
        }
        
    }//GEN-LAST:event_igualdadMouseClicked

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        clear.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        clear.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_clearMouseExited

    private void invertirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invertirMouseEntered
        invertir.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_invertirMouseEntered

    private void invertirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invertirMouseExited
        invertir.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_invertirMouseExited

    private void potenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potenciaMouseEntered
        potencia.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_potenciaMouseEntered

    private void potenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potenciaMouseExited
        potencia.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_potenciaMouseExited

    private void divisionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisionMouseEntered
        division.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_divisionMouseEntered

    private void divisionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisionMouseExited
        division.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_divisionMouseExited

    private void num1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num1MouseEntered
        num1.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_num1MouseEntered

    private void num1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num1MouseExited
        num1.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_num1MouseExited

    private void num2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num2MouseEntered
        num2.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_num2MouseEntered

    private void num2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num2MouseExited
        num2.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_num2MouseExited

    private void num3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num3MouseEntered
        num3.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_num3MouseEntered

    private void num3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num3MouseExited
        num3.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_num3MouseExited

    private void multiplicacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicacionMouseEntered
        multiplicacion.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_multiplicacionMouseEntered

    private void multiplicacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicacionMouseExited
        multiplicacion.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_multiplicacionMouseExited

    private void num4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num4MouseEntered
        num4.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_num4MouseEntered

    private void num4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num4MouseExited
        num4.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_num4MouseExited

    private void num5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num5MouseEntered
        num5.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_num5MouseEntered

    private void num5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num5MouseExited
        num5.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_num5MouseExited

    private void num6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num6MouseEntered
        num6.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_num6MouseEntered

    private void num6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num6MouseExited
        num6.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_num6MouseExited

    private void restaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaMouseEntered
        resta.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_restaMouseEntered

    private void restaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaMouseExited
        resta.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_restaMouseExited

    private void num7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num7MouseEntered
        num7.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_num7MouseEntered

    private void num7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num7MouseExited
        num7.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_num7MouseExited

    private void num8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num8MouseEntered
        num8.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_num8MouseEntered

    private void num8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num8MouseExited
        num8.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_num8MouseExited

    private void num9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num9MouseEntered
        num9.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_num9MouseEntered

    private void num9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num9MouseExited
        num9.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_num9MouseExited

    private void sumaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumaMouseEntered
        suma.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_sumaMouseEntered

    private void sumaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumaMouseExited
        suma.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_sumaMouseExited

    private void restoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restoMouseEntered
        resto.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_restoMouseEntered

    private void restoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restoMouseExited
        resto.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_restoMouseExited

    private void num0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num0MouseEntered
        num0.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_num0MouseEntered

    private void num0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num0MouseExited
        num0.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_num0MouseExited

    private void decimalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decimalMouseEntered
        decimal.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_decimalMouseEntered

    private void decimalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decimalMouseExited
        decimal.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_decimalMouseExited

    private void igualdadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igualdadMouseEntered
        igualdad.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_igualdadMouseEntered

    private void igualdadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igualdadMouseExited
        igualdad.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_igualdadMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        double n;
        double numero1;
        double numero2;
        String operacion;
        String cadena;
        double resultado;
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campo;
    private javax.swing.JButton clear;
    private javax.swing.JButton decimal;
    private javax.swing.JButton division;
    private javax.swing.JButton igualdad;
    private javax.swing.JButton invertir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton multiplicacion;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton potencia;
    private javax.swing.JButton resta;
    private javax.swing.JButton resto;
    private javax.swing.JButton suma;
    // End of variables declaration//GEN-END:variables
}
